spring.application.name=spotify-api

spring.datasource.url=jdbc:postgresql://localhost:5432/spotifydb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update


spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}